### ISSUE TITLE
autoload.php is missing

### ISSUE THREAD

**Issue by dreaming-augustin** [vamsiikrishna/html-to-bbcode#2]
In example/example.php
there is the line:`
require_once __DIR__ . '/../vendor/autoload.php';`
but autoload.php does not appear to be included in the source repository.

I managed to use this otherwise very fine library (Thanks!) by including all the files first:

```
include_once('src/ConfigurationAwareInterface.php');
include_once('src/Configuration.php');
include_once('src/Converter/ConverterInterface.php');
include_once('src/Converter/BreakConverter.php');
include_once('src/Converter/DefaultConverter.php');
include_once('src/Converter/FontConverter.php');
include_once('src/Converter/HeadConverter.php');
include_once('src/Converter/ImageConverter.php');
include_once('src/Converter/LinkConverter.php');
include_once('src/Converter/ListConverter.php');
include_once('src/Converter/ParagraphConverter.php');
include_once('src/Converter/TextStyleConverter.php');
include_once('src/ElementInterface.php');
include_once('src/Element.php');
include_once('src/Environment.php');
include_once('src/HtmlConverter.php');
```

**Comment by vamsiikrishna** [comment]
its' assumed that the user is using composer to manage their PHP library dependencies.
Once you have composer installed, you can add this library as a dependency in your projects and let composer download the source code and generating the Autoloader.

Please check out 
https://getcomposer.org/doc/00-intro.md

**Comment by dreaming-augustin** [comment]
Oh, OK. Thanks for the feedback. It's the first time I hear about composer. I am on Gentoo and Composer is only available in the unstable branch.  I will check it out.
Meanwhile, I'm guessing that there is no inconvenience in using the library without Composer, provided we manually include all the files, as I did above.

Thanks a lot for your work. :)

**Comment by dreaming-augustin** [comment]
Thanks. 
https://github.com/vamsiikrishna/html-to-bbcode/wiki
