### ISSUE TITLE
Add <em> and <strong> converters

### ISSUE THREAD

**Issue by dreaming-augustin** [vamsiikrishna/html-to-bbcode#3]
Add `<em>` and `<strong>` converters.

See attached patch:
[strong_em_converter.patch.txt](https://github.com/vamsiikrishna/html-to-bbcode/files/829960/strong_em_converter.patch.txt)

**Comment by vamsiikrishna** [comment]
hi @dreaming-augustin  , 
Thanks for the patch ! first time I am dealing with it instead of a "pull request"

I have updated the tests and created a new branch with your patch.

**Comment by vamsiikrishna** [comment]
merged .

**Comment by dreaming-augustin** [comment]
Thank you.
:)
